language: node_js
node_js: 12

addons:
  chrome: stable

before_install:
  #- export CHROME_BIN=chromium-browser
  #- export DISPLAY=:99.0

services:
 #- xvfb

before_script:
  - npm install -g @angular/cli
  - npm install -g codecov

script:
  - ng lint
  #- node_modules/karma/bin/karma start src/karma.conf.js --single-run
  - ng test --watch=false
  - ng build --prod

after_success:
  - codecov
  # - yarn packagr
  # - yarn publish

notifications:
  email:
    on_failure: change
    on_success: change